### ISSUE TITLE
A question about  SCL frequency

### ISSUE THREAD

**Issue by HIT-bangbang** [lobodol/drone-flight-controller#11]
Hello. I don't realize why you set the SCL frequency into 400KHz with changging the TWBR into 24.
I think the TWBR should be 12, and I refered to the "twi.h" and "twi.c". 
I find this sentense :
 "TWBR = ((F_CPU / TWI_FREQ) - 16) / 2;"          F_CPU = 16000000,     TWI_FREQ = 100000L .
If we want to change TWI_FREQ to 4000000, the TWBR should be 12.
Hope you teach me how to caculate, please !
Vielen Dank!

**Comment by lobodol** [comment]
Hi, setting `TWBR `is the same as using `Wire.setClock()`.

As you noticed the comment about I2C frequency is wrong.

With the formula you gave you can express `TWI_FREQ` like this: TWI_FREQ = F_CPU / (2 * TWBR + 16)

The Arduino Uno CPU clock is 16Mhz. With TWBR set to 24 the I2C clock is then
16000000 / (2 * 24 - 16) = 250 kHz

I'll update the comment soon!

**Comment by lobodol** [comment]
Thanks @HIT-bangbang for your contribution!
