### ISSUE TITLE
Need sample values 

### ISSUE THREAD

**Issue by f41ardu** [lobodol/drone-flight-controller#18]
Still working on a simulation using your code. But I need same sample data either for expected results of 
```
#ifdef ALL
    Serial.print(measures[ROLL]);
    Serial.print(",");
    Serial.print(measures[PITCH]);
    Serial.print(","); 
    Serial.print(measures[YAW]);
    Serial.print(","); 
    Serial.print(angular_motions[ROLL]);
    Serial.print(",");
    Serial.print(angular_motions[PITCH]);
    Serial.print(","); 
    Serial.println(angular_motions[YAW]);
  #endif
  #ifdef THROTTLEOUT
    Serial.print(pulse_length_esc1);
    Serial.print(",");
    Serial.print(pulse_length_esc2);
    Serial.print(","); 
    Serial.print(pulse_length_esc3);
    Serial.print(","); 
    Serial.println(pulse_length_esc4);
  #endif
```
Expectation is that if quad is at rest (let say in air - simulation) all engines get the same pulse. My result
![1](https://user-images.githubusercontent.com/6494193/153069691-c020addd-5299-4edc-bb44-a0f7482b9a56.png)
 
But I expect that esc1 .. esc4 get the same pulselenght. Throttle is set to 1300 and the rest to 1500 (Stick in middle position). 

And this are values from measures and angular_motion. 
![2](https://user-images.githubusercontent.com/6494193/153070627-088a851b-c429-49d5-8217-826ff52cb7b0.png)

Strange isn't it? 

I've tested MPU6050 using different methods and it's working fine. i.e Madwick, ....

**Comment by lobodol** [comment]
Hi, can you tell me which color is which data please?
I will do some tests tonight to compare with your results.

**Comment by f41ardu** [comment]
After stabilisation, MPU6050 at rest and with up orientation. (chip on top)
These are results from measure  
```
  measure             angular motions
rool, pitch, yaw,  roll, pitch, yaw
1.63,5.43,-0.03, 0.01,0.01,0.03
1.63,5.43,-0.08, 0.01,-0.01,0.04
1.63,5.43,0.02, 0.03,0.01,0.02
1.63,5.43,0.00, 0.03,-0.02,0.02
1.63,5.43,-0.02, 0.03,-0.04,0.02
1.63,5.43,-0.02, 0.02,-0.03,0.02
1.63,5.43,0.00, 0.02,-0.01,0.01
1.64,5.43,-0.05, 0.02,-0.02,0.02
1.64,5.43,-0.11, -0.00,-0.03,0.05
``` 
If we expect something like +/-0.0x, +/-0.0y, +/- 0.0z for measure at rest something might be broken mainly with my chip?

**Comment by f41ardu** [comment]
Solution? 

```
// To dampen the pitch and roll angles a complementary filter is used
    measures[ROLL]  = (measures[ROLL]  * 0.9 + gyro_angle[X] * 0.1)/SSF_GYRO;
    measures[PITCH] = (measures[PITCH] * 0.9 + gyro_angle[Y] * 0.1)/SSF_GYRO;
    measures[YAW]   = -gyro_raw[Z] / SSF_GYRO; // Store the angular motion for this axis
``` 
Divide measures[ROLL] and measures[PITCH] by SSF_GYRO. 

My next step is then to buld the physical hardware.

**Comment by lobodol** [comment]
I just did some tests using a digital inclinometer to compare results, angles seem correct. At least roll & pitch.

To do this, I initialized Serial at 57600 bauds and display some debug messages:

```c
setup() {
    Serial.begin(57600);

    // ...
}

loop() {
    // ...

    Serial.print(measures[YAW]);
    Serial.print(", ");
    Serial.print(measures[PITCH]);
    Serial.print(", ");
    Serial.println(measures[ROLL]);
}
```

The issue might come from elsewhere.

**Comment by f41ardu** [comment]
I would guess I found the bug. Carfull callibration is required and I would recommend to scale acc_raw and gyro_raw in function readsensor() and set SSFGYRO to 1. 

´´´
void readSensor() {
  float gres = 500.0 / 32768.0;
  float ares = 8.0 / 32768.0;
  Wire.beginTransmission(MPU_ADDRESS);
  Wire.write(0x3B);
  Wire.endTransmission(false);
  Wire.requestFrom(MPU_ADDRESS,14,true);
  // Wait until all the bytes are received
  while(Wire.available() < 14);
  acc_raw[X]=ares*(Wire.read()<<8|Wire.read()); 
  acc_raw[Y]=ares*(Wire.read()<<8|Wire.read()); 
  acc_raw[Z]=ares*(Wire.read()<<8|Wire.read()); 
  Temp=Wire.read()<<8|Wire.read();
  gyro_raw[X]=gres*(Wire.read()<<8|Wire.read()); 
  gyro_raw[Y]=gres*(Wire.read()<<8|Wire.read()); 
  gyro_raw[Z]=gres*(Wire.read()<<8|Wire.read());
}

´´´
But not tested in your code. I'll do so but not within the nex 6-8 weeks. Cause I'm working in a huge project. So you can lose this issue.
